version: '3'

services:
### Applications Code Container 
  ipfs:
      container_name: ${APPLICATION_NAME}_IPSF
      build : .
      ports:
        - "5001:5001"
        - "8080:8080"
      volumes:
        - ${DATA_SAVE_PATH}/ipfs:/data/ipfs
      networks:
        - backend
networks:
  backend:
    driver: "bridge"
volumes:
  ipfs:
    driver: "local" 